### ISSUE TITLE
landing page is dated (https://ready4r.netlify.app/ )

### ISSUE THREAD

**Issue by jimrothstein** [laderast/ready_for_r_labs#10]
a. **Location in notebook** (give file name and line number from the RStudio Project): 
*Location:*
[https://ready4r.netlify.app/](https://ready4r.netlify.app/)

b. **Description of Bug or Error**: 
*Dated material (2020)*

c. **Suggested Fix**: This could be code, spelling correction, or an edit. Be sure to include line numbers.

*Certain you are working hard on this.*
*(Future)  Note areas being updated.*

**Comment by laderast** [comment]
Thanks. It's on my list to update.

**Comment by laderast** [comment]
Updated - it now just says online.
